const defaultState = {
  name: "",
  email: "",
  phone: "",
  address: "",
  skills: "",
  skillProficiency: {},
  summary: "",
  experience: [{ company: "", role: "", duration: "", description: "" }],
  education: [{ institution: "", degree: "", field: "", year: "" }],
  projects: [{ title: "", description: "" }],
  languages: "",
  languageProficiency: {},
  profilePicture: null,
  selectedTemplate: 1,
  activeTab: "basic",
  activeExpIndex: 0,
  activeProjectIndex: 0,  
  activeEducationIndex: 0,
  isEditMode: true,
  sectionHeadings: {
    1: {
      summary: "Professional Summary",
      skills: "Skills",
      languages: "Languages",
      experience: "Experience",
      education: "Education",
      projects: "Projects",
    },
    2: {
      summary: "Summary",
      contact: "Contact Info",
      skills: "Skills",
      languages: "Languages",
      experience: "Experience",
      education: "Education",
      projects: "Projects",
    },
    3: {
      summary: "Professional Summary",
      skills: "Skills & Expertise",
      languages: "Languages",
      experience: "Work Experience",
      education: "Education",
      projects: "Projects",
    },
  },
  theme: "light",
};

export const initialState =  defaultState;
